function drawBox(coords, Calib, fillcol, linestyle, linewidth)
rectangle('Position',[coords(1); Calib.screen.height-coords(4); ...
    coords(3)-coords(1); ...
    coords(4)-coords(2)],'FaceColor', fillcol,'LineStyle', linestyle,...
    'LineWidth',linewidth)
return
